import React from "react";
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import MainLayout from "./components/MainLayout";
import Home from "./pages/Home";
import NewsApp from "./pages/NewsApp";
import NewsPage from "./pages/NewsApp/NewsPage"; 
import PlantResearch from "./pages/PlantResearch";
import Recommendations from "./pages/Recommendations";
import Dashboard from "./pages/Recommendations/Dashboard";
import Dictionary from "./pages/Recommendations/Dictionary";
import Recommender from "./pages/Recommendations/Recommender";
import Contact from "./pages/Home/Contact";
import AboutUs from "./pages/Home/AboutUs";
import HomeContent from "./pages/Home/HomeContent";

const App = () => {
  const articles = [
    { id: 1, title: "News 1", description: "This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. ", imageUrl: "/assets/images/Conservation.jpg" },
    { id: 2, title: "News 2", description: "Series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation.  2", imageUrl: "/assets/images/HomeHero3.jpg" },
    { id: 3, title: "News 3", description: "Based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation.  3", imageUrl: "/assets/images/HomeHero1.jpg" },
    { id: 4, title: "News 4", description: "Conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation.  4", imageUrl: "/assets/images/CropDiversity.jpg" },
    { id: 5, title: "News 5", description: "COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation.  5", imageUrl: "/assets/images/HomeHero2.png" },
    { id: 6, title: "News 6", description: "Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation. This is the first part of an articles series based on based on conversations held during COP16 (Cali) and COP29 (Baku) side events by leading food system actors, who explored solutions provided by agroecology. Learn why this fall is crucial for food systems governance as world leaders and food system actors gather to discuss solutions to biodiversity loss, climate change and land degradation.  6", imageUrl: "/assets/images/SustainableFarming.jpg" },
  ];


  return (
    <Router>
      <Routes>

        <Route path="/" element={<MainLayout />}>

          <Route path="news" element={<NewsApp articles={articles} />}>
            <Route index element={<NewsApp articles={articles} />} />
            <Route path="aboutus" element={<AboutUs />} />
            <Route path="contact" element={<Contact />} />  
          </Route>         
          <Route path="news/:id" element={<NewsPage articles={articles} />} />
          <Route path="plant-research" element={<PlantResearch />} />

          <Route path="/" element={<Home />}>
            <Route index element={<HomeContent />} />
            <Route path="aboutus" element={<AboutUs />} />
            <Route path="contact" element={<Contact />} />
          </Route>

          <Route path="recommendations" element={<Recommendations />}>
            <Route index element={<Dashboard />} />
            <Route path="dashboard" element={<Dashboard />} />
            <Route path="dictionary" element={<Dictionary />} />
            <Route path="recommender" element={<Recommender />} />
          </Route>

        </Route>
      </Routes>
    </Router>
  );
};

export default App;
